"""LLM-written explanation of a forecast (OpenAI Chat Completions).

The explainer only receives numbers the agent already computed and is instructed not to
invent any. Every failure mode — missing key, network, timeout, rate limit, refusal, empty
answer — surfaces as LlmExplainerError so the agent can fall back to the template explanation.

The API key is read by the OpenAI SDK itself from the OPENAI_API_KEY environment variable.
"""

import asyncio
import json
import logging
from typing import Literal, Protocol

import openai
from openai import OpenAI

logger = logging.getLogger(__name__)

_MAX_COMPLETION_TOKENS = 500  # 3–5 sentences
_LANGUAGE_NAMES: dict[str, str] = {"en": "English", "ru": "Russian"}

_SYSTEM_PROMPT = """\
You are the explanation step of WindAI, an AI agent that forecasts hourly normalized \
active power (0 = idle, 1 = rated capacity) of wind turbines 24–48 hours ahead.

You receive a JSON object with facts the agent computed for one forecast. Write a short \
explanation for a grid dispatcher: 3 to 5 sentences of plain prose, no headings, no lists, \
no markdown. Cover the expected generation level and average, when the peak is and the \
wind behind it, any low-output window, how the turbines compare if there are several, and \
the warnings. Always state whether the agent recomputed the forecast and why — or that its \
self-check found no reason to.

Use only the numbers in the JSON; never invent values, causes or times that are not there. \
Express power as a percentage of rated capacity. Answer in {language}."""


class LlmExplainerError(RuntimeError):
    """The LLM explanation is unavailable; the caller should use the template."""


class ForecastExplainer(Protocol):
    #: Shown in agent step messages, e.g. "OpenAI (gpt-4o-mini)".
    name: str

    async def explain(self, facts: dict[str, object]) -> str: ...


class OpenAIExplainer:
    def __init__(
        self,
        model: str,
        timeout_s: float,
        language: Literal["en", "ru"] = "en",
        client: OpenAI | None = None,
    ) -> None:
        # OpenAI() reads OPENAI_API_KEY from the environment; the key never passes through our code.
        self._client = client or OpenAI(max_retries=1)
        self._model = model
        self._timeout_s = timeout_s
        self._system = _SYSTEM_PROMPT.format(language=_LANGUAGE_NAMES[language])
        self.name = f"OpenAI ({model})"

    async def explain(self, facts: dict[str, object]) -> str:
        try:
            # The SDK client is synchronous: run it in a worker thread to keep the event loop free.
            completion = await asyncio.to_thread(
                self._client.chat.completions.create,
                model=self._model,
                messages=[
                    {"role": "system", "content": self._system},
                    {"role": "user", "content": json.dumps(facts, ensure_ascii=False, indent=2)},
                ],
                max_completion_tokens=_MAX_COMPLETION_TOKENS,
                timeout=self._timeout_s,
            )
        except openai.AuthenticationError as exc:
            raise LlmExplainerError("OpenAI API key was rejected") from exc
        except openai.RateLimitError as exc:
            raise LlmExplainerError("OpenAI rate limit or quota reached") from exc
        except openai.APIStatusError as exc:
            raise LlmExplainerError(f"OpenAI API error {exc.status_code}") from exc
        except openai.APIConnectionError as exc:  # includes APITimeoutError
            raise LlmExplainerError(f"OpenAI unreachable: {type(exc).__name__}") from exc

        if not completion.choices:
            raise LlmExplainerError("OpenAI returned no choices")
        choice = completion.choices[0]
        if choice.message.refusal or choice.finish_reason == "content_filter":
            raise LlmExplainerError("OpenAI declined to answer")
        if choice.finish_reason == "length":
            raise LlmExplainerError("OpenAI answer was truncated")

        text = (choice.message.content or "").strip()
        if not text:
            raise LlmExplainerError("OpenAI returned an empty answer")
        # _request_id is not guaranteed on every SDK version; logging must never break the step.
        logger.info(
            "LLM explanation generated by %s (request %s)", completion.model, getattr(completion, "_request_id", None)
        )
        return text
